/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OccasionenRouteImport } from './routes/occasionen'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OccasionenVehicleIdRouteImport } from './routes/occasionen_.$vehicleId'

const OccasionenRoute = OccasionenRouteImport.update({
  id: '/occasionen',
  path: '/occasionen',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OccasionenVehicleIdRoute = OccasionenVehicleIdRouteImport.update({
  id: '/occasionen_/$vehicleId',
  path: '/occasionen/$vehicleId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/occasionen': typeof OccasionenRoute
  '/occasionen/$vehicleId': typeof OccasionenVehicleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/occasionen': typeof OccasionenRoute
  '/occasionen/$vehicleId': typeof OccasionenVehicleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/occasionen': typeof OccasionenRoute
  '/occasionen_/$vehicleId': typeof OccasionenVehicleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/occasionen' | '/occasionen/$vehicleId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/occasionen' | '/occasionen/$vehicleId'
  id: '__root__' | '/' | '/occasionen' | '/occasionen_/$vehicleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OccasionenRoute: typeof OccasionenRoute
  OccasionenVehicleIdRoute: typeof OccasionenVehicleIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/occasionen': {
      id: '/occasionen'
      path: '/occasionen'
      fullPath: '/occasionen'
      preLoaderRoute: typeof OccasionenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/occasionen_/$vehicleId': {
      id: '/occasionen_/$vehicleId'
      path: '/occasionen/$vehicleId'
      fullPath: '/occasionen/$vehicleId'
      preLoaderRoute: typeof OccasionenVehicleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OccasionenRoute: OccasionenRoute,
  OccasionenVehicleIdRoute: OccasionenVehicleIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
