/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OccasionenRouteImport } from './routes/occasionen'
import { Route as IndexRouteImport } from './routes/index'

const OccasionenRoute = OccasionenRouteImport.update({
  id: '/occasionen',
  path: '/occasionen',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/occasionen': typeof OccasionenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/occasionen': typeof OccasionenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/occasionen': typeof OccasionenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/occasionen'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/occasionen'
  id: '__root__' | '/' | '/occasionen'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OccasionenRoute: typeof OccasionenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/occasionen': {
      id: '/occasionen'
      path: '/occasionen'
      fullPath: '/occasionen'
      preLoaderRoute: typeof OccasionenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OccasionenRoute: OccasionenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
